.gitignore
scripts/vote_2021_08_19_fund_deversifi_lexpunk_and_balancer_rewards.py
utils/evm_script.py

- Add functionality for decoding and human-readable printing for EVM scripts.
- Integrate example of decoding into the vote which was published 19.08.
Examples of output:
1. Without repeated scripts
```python
...
Callscriptfunds_in_wei
Script #1.
Contract: 0xb9e5cbb9ca5b0d659238807e84d0176930753d86
Function: newImmediatePayment
Inputs:
_token: address = 0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32
_receiver: address = 0x1dD909cDdF3dbe61aC08112dC0Fdf2Ab949f79D8
_amount: uint256 = 100000000000000000000000
_reference: string = Balancer pool LP rewards: transfer to rewards distributor contract
-----------------------------------------------------------
Script #2.
Contract: 0xb9e5cbb9ca5b0d659238807e84d0176930753d86
Function: newImmediatePayment
Inputs:
_token: address = …
```

Decoding EVM scripts before vote running

---

scripts/vote_2021_09_02.py
tests/test_2021_09_02.py
utils/evm_script.py

Vote points:
- Node Operators Registry: Add node operator named Blockdaemon with reward address `0x4f42A816dC2DBa82fF927b6996c14a741DCbD902`
- Raise key limit for Node Operator # 2 (p2p) to 4800
- Raise key limit for Node Operator # 4 (stakefish) to 6000
- Raise key limit for Node Operator # 5 (Blockscape) to 7000
- Raise key limit for Node Operator # 6 (DSRV) to 3700
- Raise key limit for Node Operator # 8 (SkillZ) to 7000
- Raise key limit for Node Operator # 9 (RockX) to 100
- Raise key limit for Node Operator # 10 (Figment) to 100
- Raise key limit for Node Operator # 11 (Allnodes) to 100
- Raise key limit for Node Operator # 12 (Anyblock) to 100
- Allocate LDO tokens (3 523 767.186 LDO) for referral rewards (to DeversiFi and Ledger) to finance address …

Vote 02/09/21

---

scripts/vote_2021_11_25.py
tests/test_2021_11_25.py

Omnibus implementation scripts on 25.11.2021
There are two payouts of the LDO tokens and one key limit raising.

feat: add voting/test scripts on 25.11.2021

---

scripts/vote_2021_11_26.py
tests/test_2021_11_26.py

Restarts 25.11.2021 vote without item #3

Add vote on 26.11.2021 (restart vote on 25.11.2021 without item #3)

---

scripts/vote_2021_12_09.py
tests/test_2021_12_09.py

Omnibus implementation scripts on 09.12.2021.
There are four payouts of the LDO tokens.

feat: add voting/test scripts on 09.12.2021

---

scripts/vote_2021_12_23.py
tests/event_validators/common.py
tests/event_validators/payout.py
tests/event_validators/repo_upgrade.py
tests/test_2021_12_23.py

Voting 23/12/2021.
1. Send 4,100 LDO to finance multisig 0x48F300bD3C52c7dA6aAbDE4B683dEB27d38B9ABb for 10,000 DAI Isidoros Passadis Nov comp
2. Allocate 6,900 (16,666 DAI * 1.2 in LDO by the spot price) LDO to finance multisig 0x48F300bD3C52c7dA6aAbDE4B683dEB27d38B9ABb for 16,666 DAI Jacob Blish Dec comp (1 DAI = X LDO)
3. Send X LDO to the financial multisig 0x48F300bD3C52c7dA6aAbDE4B683dEB27d38B9ABb  for 11th period referral rewards
4. Update Lido app IPFS hash to QmQkJMtvu4tyJvWrPXJfjLfyTWn959iayyNjp7YqNzX7pS
5. Update NOS app IPFS hash to Qma7PXHmEj4js2gjM9vtHPtqvuK82iS5EYPiJmzKLzU58G

Omnibus 2021/12/23

---

scripts/vote_2021_12_27.py
tests/test_2021_12_27.py

Restart vote on 23.12.2021 with an actual DAI-LDO price.

Add voting/test scripts on 27.12.2021

---

README.md
scripts/vote_2021_12_09.py
scripts/vote_2021_12_16.py
tests/conftest.py
utils/agent.py
utils/brownie_prelude.py
utils/config.py
utils/config_goerli.py
utils/config_mainnet.py
utils/finance.py
utils/voting.py

This PR provides possible resolution for the #18 issue.

Omnibus config cleanup

---

scripts/vote_2022_01_20.py
tests/test_2022_01_20.py
utils/voting.py

1) Allocate 5500 LDO tokens to Master of Validators Jan 2022 compensation;
2) Allocate 9200 LDO tokens to BizDev Leader Jan 2022 compensation;
3) Allocate 147245 LDO tokens for the 13th period referral rewards

add Jan 20 2022 vote script and it's test

---

utils/evm_script.py
utils/tx_tracing.py

See issue #24 for the details.

Fix: improve events data parsing for some edge-cases

---

scripts/vote_2022_03_03.py
tests/test_2022_03_03.py

1. Referral program payout of 412,082 LDO to finance multisig 0x48F300bD3C52c7dA6aAbDE4B683dEB27d38B9ABb

add voting script for 2022-03-03

---

scripts/vote_2022_03_17.py
tests/test_2022_03_17.py

Remove redundant code chunks.
Update amounts.

Fix: update voting artifacts on 17/03/2022

---

scripts/vote_2022_03_22.py
scripts/vote_2022_03_24.py
tests/conftest.py
tests/test_2022_03_22.py
utils/permissions.py

The voting script covers the following proposed actions:
1. Create role BURN_ROLE for TokenManager 0xDfe76d11b365f5e0023343A367f0b311701B3bc1
2. Burn 3,691,500 LDO tokens on 0x48Acf41D10a063f9A6B718B9AAd2e2fF5B319Ca2
3. Revoke BURN_ROLE from Voting 0xbc0B67b4553f4CF52a913DE9A6eD0057E2E758Db
Context: https://research.lido.fi/t/proposal-to-freeze-vesting-for-compromised-address/1864

feat: add vote to burn LDOs

---

scripts/vote_2022_04_16.py
tests/event_validators/unpause.py
tests/test_2022_04_16.py
tests/tx_tracing_helpers.py

WIP unpause 16 Apr 2022 vote

---

utils/voting.py

Fix error handling when voting contract sources are unknown.

Fix: improve error handling

---

scripts/vote_2022_04_16.py
scripts/vote_2022_04_19.py

chore: add execution marks

---

.github/workflows/test.yml

Automation request https://www.notion.so/Test-automation-for-scripts-7baab0d6cb924665a31f1ae9f15b0ce2

feat: Autotests on CI

---

tests/regression/test_el_rewards.py

Update regression tests for the daily-changing EL rewards balance.

Fix: post_merge el rewards regression tests

---

tests/test_legacy_oracle_skipped_report.py
utils/import_current_votes.py
utils/test/helpers.py
utils/test/oracle_report_helpers.py

https://linear.app/lidofi/issue/ETHUI-417/[contract-test]-report-after-old-oracle-skipped-report

Skipped oracle report test

---

tests/regression/test_hash_consensus_negative.py
tests/regression/test_validator_exit_bus_happy_path.py
tests/test_upgrade_template.py
utils/evm_script.py
utils/test/oracle_report_helpers.py

Added hash consensus negative tests

---

tests/regression/test_sanity_checks.py
utils/test/oracle_report_helpers.py

Sanity checks negative tests

---

scripts/upgrade_shapella.py
tests/test_upgrade_shapella.py

See README in https://github.com/lidofinance/lido-dao/tree/develop/apps

Fix: new content_uri for all apps

---

tests/acceptance/conftest.py
tests/acceptance/test_accounting_oracle.py
tests/acceptance/test_node_operators_registry.py
tests/acceptance/test_staking_router.py
tests/acceptance/test_withdrawals_negative.py
tests/conftest.py
tests/regression/conftest.py
tests/regression/test_accounting.py
tests/regression/test_all_round_happy_path.py
tests/regression/test_hash_consensus_negative.py
tests/regression/test_node-operators-registry-happy-path.py
tests/regression/test_pause_resume.py
tests/regression/test_sanity_checks.py
tests/regression/test_withdrawal_happy_path.py

Feat: post-report tests scaffolds

---

README.md

Update Readme for the new IPFS upload options

Update Readme for the new IPFS upload options

---

interfaces/csm/CSVerifier.json
tests/acceptance/test_csm.py
tests/regression/conftest.py
tests/regression/test_accounting_oracle_extra_data.py
tests/regression/test_accounting_oracle_extra_data_full_items.py
tests/regression/test_csm.py
tests/regression/test_dsm_keys_unvetting.py
tests/regression/test_sanity_checks.py
tests/regression/test_staking_router_stake_distribution.py
utils/dsm.py
utils/test/csm_helpers.py

fix target share distribution test

csm regression tests

---

tests/acceptance/test_simple_dvt_module.py
tests/regression/test_sdvt_rewards_happy_path.py
utils/test/simple_dvt_helpers.py

- Take into account isTargetLimitActive value.
- Deposit count should be big enough in case if module has many NO with dopositable keys
- Add max to 100 signing keys per transaction

Simple DVT test fixes

---

tests/acceptance/test_accounting_oracle_negative.py
tests/regression/test_accounting.py

Tests hardhat compatibility

---

scripts/fork_utils_2024_10_08.py
scripts/upgrade_2024_10_08.py
tests/_test_fallback_enable_deposits.py
tests/_test_fallback_rollback_l1.py
tests/test_2024_10_08.py

- move some help methods to the separate file
- disable deposits on fork
- small fixes

StETH on Op vote refactoring

---

scripts/fork_utils_2024_10_08.py

Allow to setup env for rehearsal

Steth on Op improve fork upgrade

---

utils/test/staking_router_helpers.py

test: simplify staking router helper

---

tests/regression/test_all_round_happy_path.py
tests/regression/test_pause_resume.py
utils/test/csm_helpers.py

fix rewards calculation with csm alive

upload csm keys with batches

---

.github/actions/brownie_fork_tests/action.yml
tests/regression/test_accounting_oracle_extra_data_full_items.py
tests/regression/test_all_round_happy_path.py
tests/regression/test_csm.py
tests/regression/test_staking_module_happy_path.py
utils/test/staking_router_helpers.py

- unhandled stake share limit
- too long csm queue
- queue higher than target share of the module
- mute csm extra data test

fix test errors:

---

.github/workflows/large_vote_ci.yml
.github/workflows/normal_vote_ci.yml
Dockerfile
README.md
hardhat.config.js
package.json
yarn.lock

1. Remove ssh from Dockerfile, tty will be used instead
2. Add Hardhat as a dependency to `package.json`
3. Use `shanghai` hardfork for local Hardhat node
4. Use `shanghai` hardfork for CI Hardhat node

Docker fixes

---

tests/regression/test_staking_module_happy_path.py
utils/dual_governance.py
utils/test/oracle_report_helpers.py

refactor: improve time window handling and remove test for stuck operators
